// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCweLzOU5Y3RIaDxDDTUfxIaco4RPWwUPw',
    appId: '1:792715011775:web:11b5edc815d1439ef7080a',
    messagingSenderId: '792715011775',
    projectId: 'jump-adventure-fd122',
    authDomain: 'jump-adventure-fd122.firebaseapp.com',
    storageBucket: 'jump-adventure-fd122.firebasestorage.app',
    measurementId: 'G-P4GN7QMY53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9OnuvXPAfyROBa1KNX0WAWV49G70oPc8',
    appId: '1:792715011775:android:fab77e96c48f177ef7080a',
    messagingSenderId: '792715011775',
    projectId: 'jump-adventure-fd122',
    storageBucket: 'jump-adventure-fd122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGP8H8CD_63jno0BoGSwBRuye6QVcbE_A',
    appId: '1:792715011775:ios:9a15fc59c1b13f85f7080a',
    messagingSenderId: '792715011775',
    projectId: 'jump-adventure-fd122',
    storageBucket: 'jump-adventure-fd122.firebasestorage.app',
    iosBundleId: 'com.hoons.jumpAdventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGP8H8CD_63jno0BoGSwBRuye6QVcbE_A',
    appId: '1:792715011775:ios:9a15fc59c1b13f85f7080a',
    messagingSenderId: '792715011775',
    projectId: 'jump-adventure-fd122',
    storageBucket: 'jump-adventure-fd122.firebasestorage.app',
    iosBundleId: 'com.hoons.jumpAdventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCweLzOU5Y3RIaDxDDTUfxIaco4RPWwUPw',
    appId: '1:792715011775:web:56a5ec4249f31a65f7080a',
    messagingSenderId: '792715011775',
    projectId: 'jump-adventure-fd122',
    authDomain: 'jump-adventure-fd122.firebaseapp.com',
    storageBucket: 'jump-adventure-fd122.firebasestorage.app',
    measurementId: 'G-W4HQQE481H',
  );

}